In [55]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.decomposition import PCA


In [56]:
data = pd.read_csv("Titanic-Dataset.csv")
print(data.head())
print(data.info())

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
<c

In [57]:
data.fillna(data.mean(numeric_only=True), inplace=True)
data.fillna(data.mode().iloc[0], inplace=True)


In [58]:
data.drop_duplicates(inplace=True)

In [59]:
numeric_cols = data.select_dtypes(include=['number']).columns
Q1 = data[numeric_cols].quantile(0.25)
Q3 = data[numeric_cols].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outlier_condition = ((data[numeric_cols] < lower_bound) | (data[numeric_cols] > upper_bound)).any(axis=1)
data = data[~outlier_condition]
data

PassengerId  Survived  Pclass  \
0              1         0       3   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
..           ...       ...     ...   
884          885         0       3   
886          887         0       2   
887          888         1       1   
889          890         1       1   
890          891         0       3   

                                             Name  Gender        Age  SibSp  \
0                         Braund, Mr. Owen Harris    male  22.000000      1   
2                          Heikkinen, Miss. Laina  female  26.000000      0   
3    Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000      1   
4                        Allen, Mr. William Henry    male  35.000000      0   
5                                Moran, Mr. James    male  29.699118      0   
..                                            ...     ...        ...    ...   
884                        Sutehall, Mr. Henry Jr    male  25.000000      0   
886                         Montvila, Rev. Juozas    male  27.000000      0   
887                  Graham, Miss. Margaret Edith  female  19.000000      0   
889                         Behr, Mr. Karl Howell    male  26.000000      0   
890                           Dooley, Mr. Patrick    male  32.000000      0   

     Parch            Ticket     Fare    Cabin Embarked  
0        0         A/5 21171   7.2500  B96 B98        S  
2        0  STON/O2. 3101282   7.9250  B96 B98        S  
3        0            113803  53.1000     C123        S  
4        0            373450   8.0500  B96 B98        S  
5        0            330877   8.4583  B96 B98        Q  
..     ...               ...      ...      ...      ...  
884      0   SOTON/OQ 392076   7.0500  B96 B98        S  
886      0            211536  13.0000  B96 B98        S  
887      0            112053  30.0000      B42        S  
889      0            111369  30.0000     C148        C  
890      0            370376   7.7500  B96 B98        Q  

[577 rows x 12 columns]

In [60]:
data1 = pd.read_csv("Titanic-Dataset.csv")
data2 = pd.read_csv("Titanic-Dataset.csv")

df = pd.merge(data1, data2, on="PassengerId")
df

PassengerId  Survived_x  Pclass_x  \
0              1           0         3   
1              2           1         1   
2              3           1         3   
3              4           1         1   
4              5           0         3   
..           ...         ...       ...   
886          887           0         2   
887          888           1         1   
888          889           0         3   
889          890           1         1   
890          891           0         3   

                                                Name_x Gender_x  Age_x  \
0                              Braund, Mr. Owen Harris     male   22.0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...   female   38.0   
2                               Heikkinen, Miss. Laina   female   26.0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)   female   35.0   
4                             Allen, Mr. William Henry     male   35.0   
..                                                 ...      ...    ...   
886                              Montvila, Rev. Juozas     male   27.0   
887                       Graham, Miss. Margaret Edith   female   19.0   
888           Johnston, Miss. Catherine Helen "Carrie"   female    NaN   
889                              Behr, Mr. Karl Howell     male   26.0   
890                                Dooley, Mr. Patrick     male   32.0   

     SibSp_x  Parch_x          Ticket_x   Fare_x  ... Pclass_y  \
0          1        0         A/5 21171   7.2500  ...        3   
1          1        0          PC 17599  71.2833  ...        1   
2          0        0  STON/O2. 3101282   7.9250  ...        3   
3          1        0            113803  53.1000  ...        1   
4          0        0            373450   8.0500  ...        3   
..       ...      ...               ...      ...  ...      ...   
886        0        0            211536  13.0000  ...        2   
887        0        0            112053  30.0000  ...        1   
888        1        2        W./C. 6607  23.4500  ...        3   
889        0        0            111369  30.0000  ...        1   
890        0        0            370376   7.7500  ...        3   

                                                Name_y  Gender_y  Age_y  \
0                              Braund, Mr. Owen Harris      male   22.0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    female   38.0   
2                               Heikkinen, Miss. Laina    female   26.0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    female   35.0   
4                             Allen, Mr. William Henry      male   35.0   
..                                                 ...       ...    ...   
886                              Montvila, Rev. Juozas      male   27.0   
887                       Graham, Miss. Margaret Edith    female   19.0   
888           Johnston, Miss. Catherine Helen "Carrie"    female    NaN   
889                              Behr, Mr. Karl Howell      male   26.0   
890                                Dooley, Mr. Patrick      male   32.0   

    SibSp_y Parch_y          Ticket_y   Fare_y  Cabin_y Embarked_y  
0         1       0         A/5 21171   7.2500      NaN          S  
1         1       0          PC 17599  71.2833      C85          C  
2         0       0  STON/O2. 3101282   7.9250      NaN          S  
3         1       0            113803  53.1000     C123          S  
4         0       0            373450   8.0500      NaN          S  
..      ...     ...               ...      ...      ...        ...  
886       0       0            211536  13.0000      NaN          S  
887       0       0            112053  30.0000      B42          S  
888       1       2        W./C. 6607  23.4500      NaN          S  
889       0       0            111369  30.0000     C148          C  
890       0       0            370376   7.7500      NaN          Q  

[891 rows x 23 columns]

In [61]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(df.select_dtypes(include='number'))
data_scaled

array([[0.        , 0.        , 1.        , ..., 0.125     , 0.        ,
        0.01415106],
       [0.0011236 , 1.        , 0.        , ..., 0.125     , 0.        ,
        0.13913574],
       [0.00224719, 1.        , 1.        , ..., 0.        , 0.        ,
        0.01546857],
       ...,
       [0.99775281, 0.        , 1.        , ..., 0.125     , 0.33333333,
        0.04577135],
       [0.9988764 , 1.        , 0.        , ..., 0.        , 0.        ,
        0.0585561 ],
       [1.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.01512699]], shape=(891, 13))

In [62]:
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df.select_dtypes(include='number'))
df_scaled


array([[-1.73010796, -0.78927234,  0.82737724, ...,  0.43279337,
        -0.47367361, -0.50244517],
       [-1.72622007,  1.2669898 , -1.56610693, ...,  0.43279337,
        -0.47367361,  0.78684529],
       [-1.72233219,  1.2669898 ,  0.82737724, ..., -0.4745452 ,
        -0.47367361, -0.48885426],
       ...,
       [ 1.72233219, -0.78927234,  0.82737724, ...,  0.43279337,
         2.00893337, -0.17626324],
       [ 1.72622007,  1.2669898 , -1.56610693, ..., -0.4745452 ,
        -0.47367361, -0.04438104],
       [ 1.73010796, -0.78927234,  0.82737724, ..., -0.4745452 ,
        -0.47367361, -0.49237783]], shape=(891, 13))

# PCA

In [63]:
np.isnan(data_scaled).sum()

np.int64(354)

In [64]:
numeric_data = data.select_dtypes(include=['number'])
numeric_data.fillna(numeric_data.median(), inplace=True)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
data_scaled = scaler.fit_transform(numeric_data)

data_scaled = pd.DataFrame(data_scaled, columns=numeric_data.columns)


data_scaled.isnull().sum()


from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X_reduced = pca.fit_transform(data_scaled)

X_reduced


array([[-0.82002679, -2.3467894 ],
       [-0.56251996, -1.5873717 ],
       [ 4.18962048, -2.00588508],
       ...,
       [ 1.85797388,  0.62743247],
       [ 2.14374005,  0.98656549],
       [-0.94853172,  1.50851544]], shape=(577, 2))